[project]
name = "mcp-server-kafka"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.1.1",
    "fastmcp>=2.11.3",
    "mcp>=1.13.0",
]
